# Generated by Django 4.0.5 on 2022-07-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torob', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppingdetail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shoppingdetail',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
