# Generated by Django 4.0.5 on 2022-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torob', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='Torob.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_views',
            field=models.ManyToManyField(related_name='recent_views', to='Torob.product'),
        ),
    ]
